// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://api.hubfy.io";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhyc3Bpd2Fua2Rua3FhZXpmaGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMTg4MDAsImV4cCI6MjA4NTg5NDgwMH0.jqNC2ApZsRSZ711mj9AMeE42Fd4xjCyimN0qwPOIa8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const debugFetch: typeof fetch = async (input, init) => {
  if (!import.meta.env.DEV) {
    return fetch(input, init);
  }

  const url = typeof input === "string" ? input : input.url;
  const method = init?.method ?? "GET";
  const isSupabase = url.startsWith(SUPABASE_URL);
  const { signal, ...restInit } = init ?? {};

  if (isSupabase) {
    console.debug("[supabase]", method, url);
  }

  try {
    // Avoid AbortError loops by stripping any incoming signal for Supabase calls.
    const response = await fetch(input, isSupabase ? restInit : init);
    if (isSupabase) {
      console.debug("[supabase]", method, url, response.status);
    }
    return response;
  } catch (error) {
    if (isSupabase) {
      console.error("[supabase]", method, url, error);
    }
    throw error;
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: debugFetch,
  },
  db: {
    // Ensure no client-side timeouts abort PostgREST requests.
    timeout: 0,
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
